apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME-VERSION
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: DEPLOYMENT_NAME
        version: "VERSION"
    spec:
      containers: 
        - name: DEPLOYMENT_NAME
          image: ksleeq21/DEPLOYMENT_NAME:VERSION
          ports:
            - name: http
              containerPort: 8000
