apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dp-devops-project-1.0.2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: dp-devops-project
        version: "1.0.2"
    spec:
      containers: 
        - name: dp-devops-project
          image: ksleeq21/devops-project:1.0.2
          ports:
            - name: http
              containerPort: 8000
