apiVersion: v1
kind: Service
metadata: 
  name: SERVICE_NAME
  labels:
    name: SERVICE_NAME
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector: 
    name: DEPLOYMENT_NAME
    version: VERSION
  type: LoadBalancer