apiVersion: v1
kind: Service
metadata: 
  name: svc-devops-project
  labels:
    name: svc-devops-project
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector: 
    name: dp-devops-project
    version: "1.0.1"
  type: LoadBalancer